package com.perfume.backend.pdf;

import com.perfume.backend.dto.request.PdfRequestDto;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class PdfTemplateBuilder {

    private static final DateTimeFormatter DATE_FMT =
            DateTimeFormatter.ofPattern("dd MMM yyyy");

    public static String build(PdfRequestDto dto) {

        String date = LocalDate.now().format(DATE_FMT);

        String oilsHtml = dto.getOils().stream()
                .map(PdfTemplateBuilder::oilCard)
                .reduce("", String::concat);

        return String.format("""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<style>
body {
  margin: 0;
  padding: 40px;
  background: #f5f5f5;
  font-family: Arial, sans-serif;
}

.panel {
  max-width: 820px;
  margin: auto;
  background: #f3b422;
  border-radius: 22px;
  padding: 28px;
}

.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.logo {
  font-size: 1.4rem;
  font-weight: 900;
}

.logo span { color: white; }

.date {
  font-weight: 700;
  font-size: 0.9rem;
}

h1 {
  text-align: center;
  margin: 18px 0 22px;
}

.grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 14px;
}

.oil-card {
  background: rgba(255,255,255,0.6);
  border-radius: 14px;
  padding: 12px;
  text-align: center;
}

.oil-name {
  font-weight: 900;
}

.oil-percent {
  font-weight: 800;
  margin-top: 6px;
}

table {
  width: 100%%;
  border-collapse: collapse;
  margin-top: 18px;
  background: rgba(255,255,255,0.6);
}

thead th {
  background: #ffc74c;
  padding: 10px;
}

tbody td {
  padding: 10px;
  border-top: 1px solid rgba(0,0,0,0.1);
}

.footer {
  margin-top: 22px;
  text-align: center;
  font-size: 0.75rem;
}
</style>
</head>

<body>
<div class="panel">

  <div class="header">
    <div class="logo">Scent<span>Lab</span></div>
    <div class="date">%s</div>
  </div>

  <h1>Your Generated Fragrance Formula</h1>

  <div class="grid">
    %s
  </div>

  <table>
    <thead>
      <tr>
        <th>Fragrance Type</th>
        <th>Concentrate</th>
        <th>Alcohol</th>
      </tr>
    </thead>
    <tbody>
      <tr><td>Cologne</td><td>3–5%%</td><td>95–97%%</td></tr>
      <tr><td>Eau de Toilette</td><td>10–12%%</td><td>88–90%%</td></tr>
      <tr><td>Eau de Parfum</td><td>15–20%%</td><td>80–85%%</td></tr>
      <tr><td>Perfume</td><td>20–30%%</td><td>70–80%%</td></tr>
    </tbody>
  </table>

  <div class="footer">
    Generated by ScentLab — Experimental fragrance assistant
  </div>

</div>
</body>
</html>
""", date, oilsHtml);
    }

    private static String oilCard(PdfRequestDto.OilLine oil) {
        return String.format("""
<div class="oil-card">
  <div class="oil-name">%s</div>
  <div class="oil-percent">%.1f%%</div>
</div>
""",
        oil.getName(),
        oil.getPercent()
        );
    }
}
