package com.perfume.backend.pdf;

import com.perfume.backend.dto.request.PdfRequestDto;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Objects;

public class PdfTemplateBuilder {

    private static final DateTimeFormatter DATE_FMT =
            DateTimeFormatter.ofPattern("dd MMM yyyy");

    public static String build(PdfRequestDto dto) {

        String date = LocalDate.now().format(DATE_FMT);

        List<PdfRequestDto.OilLine> oils = dto.getOils() == null ? List.of() : dto.getOils();

        String oilsRowsHtml = oils.stream()
                .filter(Objects::nonNull)
                .map(PdfTemplateBuilder::oilRow)
                .reduce("", String::concat);

        return String.format("""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<style>
body {
  margin: 0;
  padding: 10px;

  background: #f3b422;

  font-family: Arial, sans-serif;
  color: #111;
}

.panel {
  max-width: 820px;
  margin: auto;
  background: #ffffff;
  border-radius: 22px;
  padding: 26px;
}

.header {
  width: 100%%;
  display: table;
  padding-bottom: 12px;
  border-bottom: 2px solid #111;
  margin-bottom: 18px;
}

.header-left,
.header-right {
  display: table-cell;
  vertical-align: middle;
}

.header-left { text-align: left; }
.header-right { text-align: right; }

.logo {
  font-size: 1.55rem;
  font-weight: 900;
  color: #111;
}

.logo span { color: #f3b422; }

.tagline {
  margin-top: 4px;
  font-size: 0.82rem;
  color: #444;
  font-weight: 600;
}

.date {
  font-weight: 900;
  font-size: 0.9rem;
  padding: 0;
  border: none;
  background: transparent;
  color: #111;
}


h1 {
  text-align: center;
  margin: 18px 0 14px;
  font-size: 1.30rem;
}

/* tables premium mais simples */
.table-title {
  margin-top: 14px;
  font-weight: 900;
  font-size: 1rem;
  color: #111;
}

table {
  width: 100%%;
  show
  border-collapse: collapse;
  margin-top: 10px;
  background: #fff;
  border: 2px solid #111;
}

thead th {
  background: #ffc74c;
  padding: 10px;
  font-weight: 900;
  text-align: left;
  border-bottom: 2px solid #111;
}

tbody td {
  padding: 10px;
  border-top: 1px solid rgba(0,0,0,0.12);
  font-size: 0.9rem;
}

tbody tr:nth-child(even) {
  background: rgba(0,0,0,0.04);
}

td.percent, th.percent {
  text-align: right;
  width: 28%%;
  font-weight: 900;
}

.oils-name {
  font-weight: 900;
}

.note {
  margin-top: 10px;
  font-size: 0.78rem;
  color: #444;
}

.footer {
  margin-top: 18px;
  padding-top: 12px;
  border-top: 2px solid #111;
  text-align: center;
  font-size: 0.75rem;
  color: #444;
}
</style>
</head>

<body>
<div class="panel">

  <div class="header">
    <div class="header-left">
      <div class="logo">Parfu<span>ma</span></div>
      <div class="tagline">Premium fragrance formula sheet</div>
    </div>
    <div class="header-right">
      <div class="date">%s</div>
    </div>
  </div>

  <h1>Your Generated Fragrance Formula</h1>

  <div class="table-title">Oils breakdown</div>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th class="percent">Percentage</th>
      </tr>
    </thead>
    <tbody>
      %s
    </tbody>
  </table>

  <div class="note">
    Percentages are indicative and depend on your final dilution and maturation.
  </div>

  <div class="table-title" style="margin-top:16px;">Dilution guide</div>
  <table>
    <thead>
      <tr>
        <th>Fragrance Type</th>
        <th class="percent">Concentrate</th>
        <th class="percent">Alcohol</th>
      </tr>
    </thead>
    <tbody>
      <tr><td>Cologne</td><td class="percent">3–5%%</td><td class="percent">95–97%%</td></tr>
      <tr><td>Eau de Toilette</td><td class="percent">10–12%%</td><td class="percent">88–90%%</td></tr>
      <tr><td>Eau de Parfum</td><td class="percent">15–20%%</td><td class="percent">80–85%%</td></tr>
      <tr><td>Perfume</td><td class="percent">20–30%%</td><td class="percent">70–80%%</td></tr>
    </tbody>
  </table>

  <div class="footer">
    Generated by Parfuma — Experimental fragrance assistant
  </div>

</div>
</body>
</html>
""", date, oilsRowsHtml);
    }

    private static String oilRow(PdfRequestDto.OilLine oil) {
        String name = oil.getName() == null ? "" : oil.getName();
        Double p = oil.getPercent();
        double percent = p == null ? 0.0 : p;

        return String.format("""
<tr>
  <td class="oils-name">%s</td>
  <td class="percent">%.1f%%</td>
</tr>
""", escapeHtml(name), percent);
    }

    private static String escapeHtml(String s) {
        return s.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }
}
