INSERT INTO essential_oil (name, note_type, power, max_percent, image_url) VALUES
('Citron', 'TOP', 3, 30, 'citron.png'),
('Bergamote', 'TOP', 3, 25, 'bergamote.png'),
('Lavande', 'HEART', 2, 35, 'lavande.png'),
('Rose', 'HEART', 2, 30, 'rose.png'),
('Santal', 'BASE', 1, 25, 'santal.png'),
('Vanille', 'BASE', 1, 20, 'vanille.png'),
('Ylang-Ylang', 'HEART', 2, 30, 'ylang-ylang.png'),
('Cedre', 'BASE', 1, 25, 'cedre.png'),
('Menthe', 'TOP', 3, 20, 'menthe.png'),
('Orange Douce', 'TOP', 3, 30, 'orange-douce.png'),
('Geranium', 'HEART', 2, 30, 'geranium.png'),
('Musc', 'BASE', 1, 15, 'musc.png'),
('Eucalyptus', 'TOP', 3, 20, 'eucalyptus.png'),
('Camomille', 'HEART', 2, 25, 'camomille.png'),
('Patchouli', 'BASE', 1, 20, 'patchouli.png');